org: discoverooapi
app: discoveroo-api
service: discoveroo-api

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  getCities:
    handler: app.handler
    events:
      - http:
          path: /api/v1/cities
          method: get
          cors: true